# Generated by Django 3.2.4 on 2021-06-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['pub_year']},
        ),
    ]
